In [2]:
from prova_centerline_extraction import compute_network_centerlines, getEndPoints, aortic_arch_endpoint_check, robust_endpoint_detection
import os
from arterial.io.load_and_save_operations import *

case_dir = "/home/vhir/github/arterial/tests/test_data/output"
mode = "extracranial_vessels"

segmentation = load_vtkpolydata(os.path.join(case_dir, mode, "segmentation.vtk"))
segmentation_nifti = load_nifti(os.path.join(case_dir, mode, "segmentation.nii.gz"))
segmentation_array = segmentation_nifti.get_fdata()
segmentation_affine = segmentation_nifti.affine


print("Extracting centerline network...")
network_centerlines = compute_network_centerlines(segmentation)
print("Extracting endpoints...")
endpoints = getEndPoints(network_centerlines, None)
for idx, endpoint in enumerate(endpoints):
    endpoints[idx] = np.array(endpoint)

print("Checking presence of AA endpoints...")
endpoints = aortic_arch_endpoint_check(endpoints, segmentation_array, segmentation_affine)
print("Robust endpoint replacement...")
endpoints = robust_endpoint_detection(endpoints, segmentation_array, segmentation_affine)

Extracting centerline network...
Progress: 100%Progress: 100%
Cleaning surface.
Triangulating surface.
Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing centerlines...Computing

2024-04-30 14:13:17.148 ( 101.003s) [        757C6740]vtkvmtkSteepestDescentL:213   WARN| vtkvmtkSteepestDescentLineTracer (0x783c240): Can't find a steepest descent edge. Target not reached.
2024-04-30 14:13:17.328 ( 101.184s) [        757C6740]vtkvmtkSteepestDescentL:240   WARN| vtkvmtkSteepestDescentLineTracer (0x7821e60): Degenerate descent detected. Target not reached.
2024-04-30 14:13:17.404 ( 101.259s) [        757C6740]vtkvmtkSteepestDescentL:240   WARN| vtkvmtkSteepestDescentLineTracer (0x783c240): Degenerate descent detected. Target not reached.
2024-04-30 14:13:17.470 ( 101.325s) [        757C6740]vtkvmtkSteepestDescentL:213   WARN| vtkvmtkSteepestDescentLineTracer (0x783c240): Can't find a steepest descent edge. Target not reached.


Extracting endpoints...
Checking presence of AA endpoints...
Original startpoint is at distal AA
Robust endpoint replacement...


In [3]:
endpoints

[array([131.43125215,  97.35452756, 127.58019924]),
 array([-55.02214141, 180.80409463,  64.83758257]),
 array([ 50.17198921, 139.91091337,  66.90578234]),
 array([ 90.34980111, 140.29626116,  39.70886454]),
 array([-168.31923089,  210.56735713,   75.56765001]),
 array([-49.83421036, 187.70948476,  97.73498716]),
 array([-157.06257726,  198.86779662,   96.07047009]),
 array([-152.22832625,  204.5253578 ,  100.60465515]),
 array([-151.8633029 ,  207.03221141,  102.75964624]),
 array([-156.51243896,  176.64838257,   90.13125082]),
 array([-167.01819924,  188.63869128,   46.35105607]),
 array([-166.41105708,  189.34148331,   46.6593199 ]),
 array([ 60.6223892 , 160.70242235, 127.77886133]),
 array([-170.75549575,  214.65618984,   75.45311491]),
 array([-169.30940954,  202.83692002,  106.25183033]),
 array([-151.56737512,  170.84449332,   68.03149656]),
 array([-151.56737512,  170.84449332,   68.03149656]),
 array([-165.36829284,  186.25289749,   45.9373628 ]),
 array([-165.36829284,  186.